### ISSUE TITLE
v1.0.1.yml Updating claims should not be supported

### ISSUE THREAD

**Issue by edmolyneux** [Property-Data-Trust-Framework/api#3]
https://github.com/Property-Data-Trust-Framework/api/blob/196423fdfd02b2ad7aa256da251740062cdfae2c/pdtf-baseline-api-1.0.1.yml#L60-L94

Per the framework spec there should not be the ability to update a claim that's already been made, since they should be immutable to provide a proper audit trail

**Comment by Reynodes** [comment]
For standard DB agree. As a DLT orchestration provider claims / all data is immutable and therefore the patch function "evolves" a current state rather than overwrites it. This enables a linked history of individual claims over time, proving a good audit trail. But as this is a generic example probably worth removing the patch function.
